services:
  server:
    image: ${IMAGE:-registry.gitlab.brojor.me/apps/dca-bot:latest}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      KEY_NAME: ${KEY_NAME}
      PRIVATE_KEY: ${PRIVATE_KEY}
    ports:
      - 127.0.0.1:3001:3000
